### ISSUE TITLE
Occassional 404 with a simple route

### ISSUE THREAD

**Issue by vascowhite** [rdlowrey/Arya#37]
I'm not sure if this is an issue with Arya or FastRoute, but I thought I'd start here to get the ball rolling.

I have the following simple route on a vagrant vm:-

````php
$app->route('GET', '/{page}', function($page){
    var_dump($page);
});
`````

If I go to `http://localhost:8000/test` I get:-

> string 'test' (length=4)

as expected.

However, if I go to `http://localhost:8000/articles` I get a 404!

Any idea what is happening here?

**Comment by RonnieSkansing** [comment]
I have tried to recreate your issue with a clone of the newst version without success. 
Using exactly the same code as your provided.

One thing that you should notice is *"Arya actively prevents the manual output of response data via output buffering. If your application generates any output (including error output) the result is a 500 Internal Server Error response. "*

Using
```
use Arya\Application;
$app = new Application;
$app->route('GET', '/{page}', function($page) {
    return $page;
});
$app->run();
```
Output tests and articles as expected.

**Comment by kelunik** [comment]
Which version of PHP is this code running on? Just checking, because there's some weird bug in php7 that could be responsible for such a behavior.

**Comment by RonnieSkansing** [comment]
My code was tested against 5.6.4 and 7.0.0-dev build yesterday

**Comment by vascowhite** [comment]
I am running this on PHP 5.5.20.

Thanks for the replies. Ronnie, the code you posted is pretty much what I am testing with, I have cut back to the simplest possible to try and isolate this problem. Even this shows the same behaviour:-

````php
use Arya\Application;
$app = new Application;
$app->route('GET', '/{page}', function($page) {
    return $page;
});
$app->run();
````

It is puzzling that only certain strings in the url cause this, I would expect it to either work or not work.

Sorry if my replies are slow, we are moving house in two days time, so we're a bit busy :)

**Comment by staabm** [comment]
Maybe some rewrite rules are kickin in sometimes?

**Comment by kelunik** [comment]
@staabm could be right. Could you please post your server configuration?

**Comment by vascowhite** [comment]
@staabm  I hadn't thought of that.
@kelunik My server config (Apache2):-

````
<VirtualHost *:80>
    DocumentRoot /vagrant/public_html
    <Directory /vagrant/public_html>
        Options FollowSymLinks
        order allow,deny
        allow from all
    </Directory>
    FallbackResource /index.php

    ErrorLog /vagrant/log/error.log
    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel debug
    CustomLog /vagrant/log/access.log combined
</VirtualHost>
````

And .htaccess:-

````
RewriteEngine on
RewriteRule !\.(js|ico|gif|jpg|png|css|svg|pdf)$ index.php
````

**Comment by vascowhite** [comment]
I used curl to eliminate browser behaviour and got the following results:-

`curl http://localhost:8000/home` gave:-

>home

as expected. However, `curl http://localhost:8000/articles` gave:-

````
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://localhost:8000/articles/">here</a>.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at localhost Port 8000</address>
</body></html>
````
So something is generating a redirect `articles/` which doesn't exist, hence the 404.

I'll keep digging as and when I can.

**Comment by kelunik** [comment]
Do you have any directories inside your folder that contains `index.php`?

**Comment by vascowhite** [comment]
@kelunik No, but there is a directory called articles. Deleting it has removed the problem, well spotted!
That was definitely unexpected behaviour!

**Comment by staabm** [comment]
@vascowhite so we can close this issue for now?

**Comment by vascowhite** [comment]
Yes, it can be closed. It was server behaviour rather than an issue with
the framework, but thanks for all the help anyway. These things seem
obvious once you hit on the problem :)

**Comment by rdlowrey** [comment]
:+1:
